import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import LanguageSwitcher from "./components/LangSwitcher";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next CRUD RTL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-3xl mx-auto text-slate-800">
          <header className="p-6 items-center border-b flex justify-between  bg-emerald-700 rounded-bl-lg rounded-br-lg">
            <Link className="text-2xl font-bold text-white" href={"/"}>
              DataForge
            </Link>
            <div className="flex items-center gap-4">
              <Link
                className="bg-slate-100 grid place-items-center py-2 px-4 rounded-full font-bold shadow-md"
                href={"/create"}
              >
                Add New
              </Link>
              <LanguageSwitcher />
            </div>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
